
services:
  backend:
    image: ${PROD_IMAGE}
    container_name: ats_fastapi
    platform: linux/amd64
    command: poetry run uvicorn ats_ai.app_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
#      - .:/ats-ai
      - .:/app
    restart: unless-stopped

  ui:
    image: ${PROD_IMAGE}
    platform: linux/amd64
    container_name: ats_streamlit
    command: poetry run streamlit run ats_ai/streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    volumes:
#      - .:/ats-ai
      - .:/app
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
