
services:
  backend:
    image: ramdorak571/ats_ai_base:0.2.3
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: ats_fastapi
    platform: linux/amd64
    command: poetry run uvicorn ats_ai.app_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/ats_ai
    restart: unless-stopped

  ui:
    image: ramdorak571/ats_ai_base:0.2.3
    platform: linux/amd64
    container_name: ats_streamlit
    command: poetry run streamlit run ats_ai/streamlit_app.py --server.port 8501
    ports:
      - "8501:8501"
    volumes:
      - .:/ats_ai
    restart: unless-stopped
