
services:
# ollama:
#   image: ollama/ollama
#   container_name: ollama
#   restart: always
#   ports:
#     - "11434:11434"

 app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: ats_ai
  command: ./start.sh
  ports:
    - "8000:8000"   # FastAPI
    - "8501:8501"   # Streamlit
  volumes:
    - .:/ats_ai        # Mount local code and ..logs
  restart: unless-stopped
#  depends_on:
#    - ollama
#  environment:
#    - OLLAMA_HOST=http://ollama:11434