version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./jd:/app/jd
      - ./jd_json:/app/jd_json
    restart: always

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
